import Head from 'next/head';
import Homepage from './homepage';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Frontend Mentor | Scoot</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Lexend+Deca&family=Space+Mono:ital,wght@0,700;1,400&display=swap" rel="stylesheet" />
			</Head>

			<Homepage />
		</div>
	);
}
